# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

ARG BASE_VERSION=15
FROM ghcr.io/daemonless/base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG PKG_NAME="lldap"
ARG PACKAGES="zstd ${PKG_NAME}"
ARG APP_VERSION="latest"
#ARG DOWNLOAD_URL="https://example.com/lldap-${APP_VERSION}.tar.gz"

ENV LLDAP_CONFIG_FILE="/config/lldap_config.toml"

LABEL org.opencontainers.image.title="lldap" \
      org.opencontainers.image.description="This project is a lightweight authentication server that provides an opinionated, simplified LDAP interface for authentication." \
      org.opencontainers.image.source="https://github.com/daemonless/lldap" \
      org.opencontainers.image.url="https://github.com/lldap/lldap" \
      org.opencontainers.image.licenses="GPL-3.0-only" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.upstream-mode=pkg \
      io.daemonless.category="Infrastructure" \
      io.daemonless.port="17170" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.packages="${PACKAGES}"
      

# Update to latest patch level
RUN pkg update -r FreeBSD-base && \
    pkg upgrade -y -r FreeBSD-base && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Install lldap from FreeBSD packages (pkg handles all dependencies)
RUN pkg update && \
    pkg install -y ${PACKAGES} && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Create version info
RUN LLDAP_VERSION=$(pkg info "${PKG_NAME}" | sed -n 's/.*Version.*: *//p') && \
    mkdir -m 0755 -p /app && echo "$LLDAP_VERSION" > /app/version


RUN cp -r /usr/local/lldap_server/lldap /usr/local/lldap_server/app \
          /usr/local/bin/lldap_migration_tool /usr/local/bin/lldap_set_password \
          /app

# Copy root filesystem
COPY root/ /

# Set permissions
RUN chmod +x /etc/services.d/lldap/run /etc/cont-init.d/* /healthz

# --- Expose (Injected by Generator) ---
EXPOSE 17170 3890

# --- Volumes (Injected by Generator) ---
VOLUME /config